# -*- coding: utf-8 -*-
"""water_sim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgpr2_Fh_9243B5LXgsNgIhjYAqujS9R
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

import copy

import numpy as np
from scipy.spatial import ConvexHull


def normalise(v):
    n = np.linalg.norm(v)
    return v / n if n > 0 else v

def generate_points_on_sphere(n=100, r=1.0):
    idx = np.linspace(0, n - 1, n)

    y = 1 - (idx / float(n - 1)) * 2  # y goes from 1 to -1
    radius = np.sqrt(1 - y * y)  # radius at y
    phi = idx * 3.6  # golden angle increment
    x = np.cos(phi) * radius
    z = np.sin(phi) * radius
    points = np.stack((x, y, z), axis=1) * r
    return points.astype(np.float32)



def generate_polyhedron(n_vertices=8, radius=1.0):
    """
    Generate a random convex polyhedron using n random points on the sphere.
    Returns (vertices, faces, neighbours) in the same format as before.
    """

    # Generate n random points on the sphere
    points = generate_points_on_sphere(n=n_vertices, r=radius)
    hull = ConvexHull(points)
    vertices = points.astype(np.float32)
    faces = hull.simplices  # Each row is a triangle (3 indices)
    # Build neighbours from faces
    neighbours = {i: set() for i in range(len(vertices))}
    for tri in faces:
        for k in range(3):
            i = tri[k]
            j = tri[(k + 1) % 3]
            neighbours[i].add(j)
            neighbours[j].add(i)
    # Convert sets to sorted lists
    neighbours = {i: sorted(list(nbs)) for i, nbs in neighbours.items()}
    return vertices, faces, neighbours


def compute_cotangent_weights(vertices, faces):
    """
    Compute cotangent weights for each edge in the mesh.
    Returns a dict of dicts: weights[i][j] = cotangent weight for edge (i, j)
    """
    from collections import defaultdict

    weights = defaultdict(dict)
    # faces: (F, 3), vertices: (V, 3)
    v0 = vertices[faces[:, 0]]  # (F, 3)
    v1 = vertices[faces[:, 1]]
    v2 = vertices[faces[:, 2]]

    # For each face, compute edge vectors
    e0 = v1 - v0  # edge from v0 to v1
    e1 = v2 - v1  # edge from v1 to v2
    e2 = v0 - v2  # edge from v2 to v0

    # For each angle, compute cotangent at each vertex
    # angle at v0, opposite edge e1
    cot0 = np.einsum("ij,ij->i", v1 - v0, v2 - v0) / np.linalg.norm(
        np.cross(v1 - v0, v2 - v0), axis=1
    )
    # angle at v1, opposite edge e2
    cot1 = np.einsum("ij,ij->i", v2 - v1, v0 - v1) / np.linalg.norm(
        np.cross(v2 - v1, v0 - v1), axis=1
    )
    # angle at v2, opposite edge e0
    cot2 = np.einsum("ij,ij->i", v0 - v2, v1 - v2) / np.linalg.norm(
        np.cross(v0 - v2, v1 - v2), axis=1
    )

    # Replace any nan or inf with 0
    cot0 = np.nan_to_num(cot0)
    cot1 = np.nan_to_num(cot1)
    cot2 = np.nan_to_num(cot2)

    # For each face, accumulate weights for each edge (i, j)
    for f, face in enumerate(faces):
        i0, i1, i2 = face
        # edge (i0, i1), opposite angle at i2
        w = cot2[f] / 2.0
        weights[i0][i1] = weights[i0].get(i1, 0.0) + w
        weights[i1][i0] = weights[i1].get(i0, 0.0) + w
        # edge (i1, i2), opposite angle at i0
        w = cot0[f] / 2.0
        weights[i1][i2] = weights[i1].get(i2, 0.0) + w
        weights[i2][i1] = weights[i2].get(i1, 0.0) + w
        # edge (i2, i0), opposite angle at i1
        w = cot1[f] / 2.0
        weights[i2][i0] = weights[i2].get(i0, 0.0) + w
        weights[i0][i2] = weights[i0].get(i2, 0.0) + w
    return weights


def step(
    velocities,
    positions,
    neighbours,
    cotangent_weights,
    dt=0.01,
    g=np.array([0, 0, -9.81]),
    friction_coeff=0.2,
    mu=0.3,
    nabla=0.05,
):

    new_velocities = copy.deepcopy(velocities)
    new_positions = copy.deepcopy(positions)

    # gravity:
    new_velocities += g * dt

    # collision with surface at z=0:
    for i in range(len(positions)):
        if positions[i][2] <= 0:
            positions[i][2] = 0  # prevent sinking below the surface
            # TODO: replace this with a more complex surface, like slope
            new_velocities[i] -= np.dot(velocities[i], np.array([0, 0, 1])) * np.array(
                [0, 0, 1]
            )  # simple collision response
            if np.linalg.norm(new_velocities[i]) < friction_coeff:
                new_velocities[i] = np.array(
                    [0, 0, 0]
                )  # stop if velocity is low enough to simulate friction
            else:
                new_velocities[i] -= friction_coeff * normalise(
                    new_velocities[i]
                )  # apply friction
            # add surface viscosity using cotangent weights:
            # mu ~ 0.3-0.5, nabla ~ 0.0-0.1
            laplacian = np.zeros_like(velocities[i])
            weight_sum = 0.0
            for j in neighbours[i]:
                w = cotangent_weights[i][j] if j in cotangent_weights[i] else 1.0
                laplacian += w * (velocities[j] - velocities[i])
                weight_sum += w
            if weight_sum > 0:
                laplacian /= weight_sum
            new_velocities[i] = (1.0 - mu * dt) * velocities[i] + nabla * dt * laplacian

    new_positions += (new_velocities - velocities) * dt

    return new_velocities, new_positions

# Initialize simulation
def init_sim():
    # vertices, faces, neighbours = generate_cube(width=1.0)
    vertices, faces, neighbours = generate_polyhedron(n_vertices=20, radius=1.0)
    velocities = np.zeros_like(vertices)
    cotangent_weights = compute_cotangent_weights(vertices, faces)
    return vertices, velocities, neighbours, cotangent_weights, faces

positions, velocities, neighbours, cotangent_weights, faces = init_sim()

# Lift the object up a bit to avoid initial collision with the floor
positions += np.array([0, 0, 1.0])

fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

sc = ax.scatter(positions[:, 0], positions[:, 1], positions[:, 2], c="b", s=60)

ax.set_xlim(-1, 1)
ax.set_ylim(-1, 1)
ax.set_zlim(-1, 1)
ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")
ax.set_title("Water Sim Points (3D)")

plt.show()

# Simulation parameters
dt = 0.05
g = np.array([0, 0, -9.81])
friction_coeff = 0.2
mu = 0.3
nabla = 0.05

from mpl_toolkits.mplot3d.art3d import Line3DCollection

def get_edge_segments(pos, faces):
    # Extract the triangles and create segments for the three edges of each face
    return pos[faces[:, [0, 1, 1, 2, 2, 0]]].reshape(-1, 2, 3)

def update(frame):
    global positions, velocities
    velocities, positions = step(
        velocities,
        positions,
        neighbours,
        cotangent_weights,
        dt=dt,
        g=g,
        friction_coeff=friction_coeff,
        mu=mu,
        nabla=nabla,
    )
    # Update point positions
    sc._offsets3d = (positions[:, 0], positions[:, 1], positions[:, 2])

    # Update line segments for the edges
    segments = get_edge_segments(positions, faces)
    lines.set_segments(segments)

    return sc, lines

from IPython.display import display, HTML
import matplotlib
from mpl_toolkits.mplot3d.art3d import Line3DCollection

# Increase the limit for animations (set to 50MB)
matplotlib.rcParams['animation.embed_limit'] = 50.0

# Re-initialize plot
fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

# Get initial faces from the sim state
segments = get_edge_segments(positions, faces)
lines = Line3DCollection(segments, colors="lightblue", linewidths=0.5, alpha=0.5)
ax.add_collection3d(lines)

# Scatter for vertices
sc = ax.scatter(positions[:, 0], positions[:, 1], positions[:, 2], c="b", s=40)

ax.set_xlim(-1, 1)
ax.set_ylim(-1, 1)
ax.set_zlim(-1, 1)

ani = FuncAnimation(fig, update, frames=200, interval=30, blit=False)
plt.close()

display(HTML(ani.to_jshtml()))